### ISSUE TITLE
Enhanced Antenna Deployer Functionality

### ISSUE THREAD

**Issue by Nicolas-M1** [TJREVERB/pfs-rewrite#23]
- [x] Make antenna deployer .functional more comprehensive (i.e. check more than just the i2c's existance)
- [x] Run command to check if the antennae have already been deployed in init (at least 3 deployed), if so update SFR
- [ ] Only deploy undeployed antennae when driver function is called

**Comment by Alan-JH** [comment]
- [ ] Debug antenna deployer read, seems to only return 255, may be hardware issue

**Comment by Alan-JH** [comment]
Definitely a hardware issue
