### ISSUE TITLE
Add locked on/off devices dictionaries

### ISSUE THREAD

**Issue by Nicolas-M1** [TJREVERB/pfs-rewrite#25]
- [x] Save whether devices are locked ON or OFF
- [x] make multiple commands
- [x] Ensure locked devices are not checked in systems check
- [x] Lock certain devices off if they aren't working (i.e. IMU)
- [x] Power on devices which are locked on at boot
- [x] Encode locked devices for transmission to ground

**Comment by nik875** [comment]
Can we just have the dictionary store 0, 1, or 2 instead of a boolean? 0 means unlocked, 1 means locked off, 2 means locked on.

**Comment by nik875** [comment]
Check device_lock branch for a partial implementation

**Comment by Nicolas-M1** [comment]
No. I used sets, which make much more sense in this context

**Comment by Nicolas-M1** [comment]
Also, please don't start checking stuff off, there's a reason why I did not add you as an assignee

**Comment by Nicolas-M1** [comment]
Implemented using two sets, one for locked on and one for locked off devices
