### ISSUE TITLE
Fix iridium encoding to handle NaN values sent from geolocation, add some sort of exception

### ISSUE THREAD

**Issue by KareemSaysHi** [TJREVERB/pfs-rewrite#29]

**Comment by The-A44** [comment]
It now should log "NaN" for the location data

**Comment by Alan-JH** [comment]
Do NOT log string data, log zeros instead. Not sure where it returns NaN, sounds like something nikhil imported. Just replace it with all zeros

**Comment by Alan-JH** [comment]
Iridium encoding cant handle string data mixed with floats
